apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
  namespace: nextcloud
data:
  DB_USER: nextcloud
  DB_NAME: nextcloud
  NC_ADMIN_USER: test


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-post-config
  namespace: nextcloud
data:
  nextcloud-post_config.sh: |
    #!/bin/bash
    su www-data -s /bin/bash -c '/var/www/html/occ config:system:set trusted_domains 0 --value=localhost'
    su www-data -s /bin/bash -c '/var/www/html/occ config:system:set trusted_domains 1 --value=nextcloud.kube.home'
    su www-data -s /bin/bash -c '/var/www/html/occ config:system:set trusted_domains 2 --value=192.168.5.145'
    su www-data -s /bin/bash -c '/var/www/html/occ config:system:set trusted_domains 3 --value=$KUBE_IP_POD'

