apiVersion: v1
kind: Service
metadata:
  name: nextcloud-app-svc
  namespace: nextcloud
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: "192.168.5.145"
  selector:
    name: nextcloud-app

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-app-ingress-svc
  namespace: nextcloud
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    name: nextcloud-app

