apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: nextcloud
spec:
  storageClassName: "sc-nextcloud"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi