apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-svc
  namespace: nextcloud
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    name: postgresql-nc