apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
data:
  DB_ROOT_PASSWORD: VGVzdERCMTIzCg==        ### echo "TestDB123" |base64
  DB_PASSWORD: UGFzc05DQDEyMwo=             ### echo "PassNC@123" |base64
  NC_ADMIN_PASSWORD: VGVzdDEyMwo=           ### echo "Test123" |base64